version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0.0

jobs:
  build_test:
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - run:
          name: run npm build
          command: cd ./app && npm install && npm run build 
      - run:
          name: run npm test
          command: cd ./app && npm run test 

  build_deploy:
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_REGION
      - run:
          name: run npm build
          command: cd ./app && npm install && npm run build 
      - run:
          name: deploy s3
          command: aws s3 sync ./app/build s3://ci-cd-example3     

workflows:
  build_test:
    jobs:
      - build_test       
      - build_deploy:
          requires:
            - build_test